version: '3'
services:
  eureka-1:
    build: ./eureka
    image: eureka:latest
    container_name: eureka-1
    ports:
      - 8781:8781
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
    networks:
      - eureka-network

  eureka-2:
    build: ./eureka
    image: eureka:latest
    container_name: eureka-2
    ports:
      - 8782:8782
    environment:
      - SPRING_PROFILES_ACTIVE=peer2
    networks:
      - eureka-network
    depends_on:
      - eureka-1

  postgres:
    image: postgres:11
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - eureka-network

#  jaeger:
#    image: jaegertracing/all-in-one
#    container_name: jaeger
#    ports:
#      - 9411:9411
#      - 16686:16686
#    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
#    networks:
#      - request-tracing-network
#      - eureka-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mem
    networks:
      - request-tracing-network
      - eureka-network

networks:
  eureka-network:
  request-tracing-network:

volumes:
  db-data: