version: '3.3'
services:
  eureka-1:
    build: ./eureka
    image: eureka:latest
    container_name: eureka-1
    ports:
    - 8781:8781
    environment:
    - SPRING_PROFILES_ACTIVE=peer1
    networks:
    - eureka-network

  eureka-2:
    build: ./eureka
    image: eureka:latest
    container_name: eureka-2
    ports:
    - 8782:8782
    environment:
    - SPRING_PROFILES_ACTIVE=peer2
    networks:
    - eureka-network
    depends_on:
    - eureka-1

  #  turbine:
  #    build: ./turbine
  #    image: turbine:latest
  #    container_name: turbine
  #    ports:
  #      - 8010:8010
  #    networks:
  #      - eureka-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - 9411:9411
    environment:
    - STORAGE_TYPE=mem
    networks:
    - zipkin-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    container_name: elastic
    volumes:
    - ./elk/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.0
    container_name: logstash
    volumes:
    - ./elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./elk/logstash/pipelines.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
    - "4560:4560"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk
    depends_on:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.0
    container_name: kibana
    ports:
    - "5601:5601"
    volumes:
    - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
    - elk

networks:
  eureka-network:
  zipkin-network:
  elk:
