version: '3'
services:
  eureka-1:
    build: ./eureka
    image: eureka:latest
    container_name: eureka-1
    ports:
      - 8781:8781
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
    networks:
      - eureka-network

  eureka-2:
    build: ./eureka
    image: eureka:latest
    container_name: eureka-2
    ports:
      - 8782:8782
    environment:
      - SPRING_PROFILES_ACTIVE=peer2
    networks:
      - eureka-network
    depends_on:
      - eureka-1

#  turbine:
#    build: ./turbine
#    image: turbine:latest
#    container_name: turbine
#    ports:
#      - 8010:8010
#    networks:
#      - eureka-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin-network

networks:
  eureka-network:
  zipkin-network:
