version: '3.3'
services:
#  eureka-1:
#    build: ./eureka
#    image: eureka:latest
#    container_name: eureka-1
#    ports:
#    - 8781:8781
#    environment:
#    - SPRING_PROFILES_ACTIVE=peer1
#    networks:
#    - eureka-network
#
#  eureka-2:
#    build: ./eureka
#    image: eureka:latest
#    container_name: eureka-2
#    ports:
#    - 8782:8782
#    environment:
#    - SPRING_PROFILES_ACTIVE=peer2
#    networks:
#    - eureka-network
#    depends_on:
#    - eureka-1

  #  turbine:
  #    build: ./turbine
  #    image: turbine:latest
  #    container_name: turbine
  #    ports:
  #      - 8010:8010
  #    networks:
  #      - eureka-network

#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#    - 9411:9411
#    environment:
#    - STORAGE_TYPE=mem
#    networks:
#    - zipkin-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    ports:
    - "9200:9200"
    - "9300:9300"
    configs:
    - source: elastic_config
      target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.0
    configs:
    - source: logstash_config
      target: /usr/share/logstash/config/logstash.yml
    - source: logstash_pipeline
      target: /usr/share/logstash/pipeline/logstash.conf
    ports:
    - "5000:5000"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk
    depends_on:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.0
    ports:
    - "5601:5601"
    configs:
    - source: kibana_config
      target: /usr/share/kibana/config/elasticsearch.yml
    networks:
    - elk

configs:
  elastic_config:
    file: ./elk/elastic/elasticsearch.yml
  logstash_config:
    file: ./elk/logstash/logstash.yml
  logstash_pipeline:
    file: ./elk/logstash/pipeline.conf
  kibana_config:
    file: ./elk/kibana/kibana.yml

networks:
  eureka-network:
  zipkin-network:
  elk:
