global:
  scrape_interval: 5s
  external_labels:
    monitor: 'services-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: manager
      password: 'test'
    static_configs:
      - targets: ['order-service:8070', 'store-service:8090', 'warehouse-service:8060', 'warranty-service:8050']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']